# Generated by Django 5.0.1 on 2024-01-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='key_skills',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='published_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='salary_from',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='salary_to',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
