# Generated by Django 5.0.1 on 2024-01-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_alter_vacancies_key_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='salary_from',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
