# Generated by Django 5.0.1 on 2024-01-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AddField(
            model_name='vacancies',
            name='course',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
