# Generated by Django 5.0.1 on 2024-01-22 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_delete_course_vacancies_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=10, unique=True)),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacancies.currencyrate'),
        ),
    ]
